# Generated by Django 5.0.3 on 2024-04-25 07:59

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        blank=True, default=datetime.datetime.now, null=True
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        blank=True, default=datetime.datetime.now, null=True
                    ),
                ),
                ("title", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                ("type", models.TextField(blank=True, null=True)),
                ("year", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": '"databank"."Board"',
            },
        ),
        migrations.CreateModel(
            name="Subtype",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        blank=True, default=datetime.datetime.now, null=True
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        blank=True, default=datetime.datetime.now, null=True
                    ),
                ),
                ("name", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": '"databank"."subtype"',
            },
        ),
        migrations.CreateModel(
            name="BoardManufacturer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        blank=True, default=datetime.datetime.now, null=True
                    ),
                ),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dot_app.board"
                    ),
                ),
            ],
            options={
                "db_table": '"databank"."board_manufacturer"',
            },
        ),
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        blank=True, default=datetime.datetime.now, null=True
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        blank=True, default=datetime.datetime.now, null=True
                    ),
                ),
                ("title", models.TextField()),
                (
                    "boards",
                    models.ManyToManyField(
                        through="dot_app.BoardManufacturer", to="dot_app.board"
                    ),
                ),
            ],
            options={
                "db_table": '"databank"."Manufacturer"',
            },
        ),
        migrations.AddField(
            model_name="boardmanufacturer",
            name="manufacturer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dot_app.manufacturer"
            ),
        ),
        migrations.AddField(
            model_name="board",
            name="manufacturers",
            field=models.ManyToManyField(
                through="dot_app.BoardManufacturer", to="dot_app.manufacturer"
            ),
        ),
        migrations.CreateModel(
            name="BoardSubtype",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        blank=True, default=datetime.datetime.now, null=True
                    ),
                ),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dot_app.board"
                    ),
                ),
                (
                    "subtype",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dot_app.subtype",
                    ),
                ),
            ],
            options={
                "db_table": '"databank"."board_subtype"',
                "unique_together": {("board", "subtype")},
            },
        ),
        migrations.AddField(
            model_name="board",
            name="subtypes",
            field=models.ManyToManyField(
                through="dot_app.BoardSubtype", to="dot_app.subtype"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="boardmanufacturer",
            unique_together={("board", "manufacturer")},
        ),
    ]
