# Generated by Django 5.0.3 on 2024-04-28 21:06

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dot_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoardBoard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        blank=True, default=datetime.datetime.now, null=True
                    ),
                ),
                (
                    "compatibleboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compatible_type_board",
                        to="dot_app.board",
                    ),
                ),
                (
                    "theboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dot_app.board"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
