# Generated by Django 4.2.13 on 2024-06-15 09:09

from django.db import migrations, models
import django_minio_backend.models


class Migration(migrations.Migration):
    dependencies = [
        ("dot_app", "0002_manufacturer_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=django_minio_backend.models.MinioBackend(bucket_name="static"),
                upload_to=django_minio_backend.models.iso_date_prefix,
            ),
        ),
    ]
