# Generated by Django 4.2.13 on 2024-06-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dot_app", "0003_alter_board_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="subtype",
            name="video_link",
            field=models.TextField(blank=True, null=True),
        ),
    ]
