# Generated by Django 4.2.13 on 2024-06-17 04:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dot_app", "0004_subtype_video_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subtype",
            name="description",
            field=models.TextField(blank=True, default="None provided.", null=True),
        ),
    ]
