# Generated by Django 4.2.13 on 2024-05-25 19:16

from django.db import migrations, models
import django_minio_backend.models


class Migration(migrations.Migration):
    dependencies = [
        ("dot_app", "0007_alter_board_created_alter_board_modified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="datasheet",
            field=models.FileField(
                blank=True,
                null=True,
                storage=django_minio_backend.models.MinioBackend(bucket_name="static"),
                upload_to=django_minio_backend.models.iso_date_prefix,
            ),
        ),
        migrations.AddField(
            model_name="board",
            name="image",
            field=models.FileField(
                blank=True,
                null=True,
                storage=django_minio_backend.models.MinioBackend(bucket_name="static"),
                upload_to=django_minio_backend.models.iso_date_prefix,
            ),
        ),
    ]
